version: '3.8'

services:
  mysql:
    image: mariadb
    container_name: "local-mariadb"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma:/data